import type { Patch } from "./types";

export const PRESETS: Patch[] = [
  {
    name: "Bright Lead",
    description: "Immediate saw lead with a little width and bite.",
    waveform: "sawtooth",
    detune: 8,
    osc2Mix: 0.42,
    subMix: 0.12,
    noiseMix: 0,
    cutoff: 2800,
    resonance: 1.6,
    filterType: "lowpass",
    filterEnv: 0.38,
    attack: 0.01,
    decay: 0.18,
    sustain: 0.58,
    release: 0.28,
  },
  {
    name: "Warm Pad",
    description: "Slow analog wash. Hold a chord and let it bloom.",
    waveform: "sawtooth",
    detune: 14,
    osc2Mix: 0.55,
    subMix: 0.18,
    noiseMix: 0.04,
    cutoff: 1100,
    resonance: 0.9,
    filterType: "lowpass",
    filterEnv: 0.22,
    attack: 0.48,
    decay: 0.42,
    sustain: 0.78,
    release: 1.7,
  },
  {
    name: "Pluck",
    description: "Short decaying triangle. Good for riffs and arps.",
    waveform: "triangle",
    detune: 4,
    osc2Mix: 0.2,
    subMix: 0.1,
    noiseMix: 0,
    cutoff: 2400,
    resonance: 1.5,
    filterType: "lowpass",
    filterEnv: 0.72,
    attack: 0.005,
    decay: 0.26,
    sustain: 0.06,
    release: 0.16,
  },
  {
    name: "Acid",
    description: "Resonant square bass. Play staccato on the low keys.",
    waveform: "square",
    detune: 0,
    osc2Mix: 0,
    subMix: 0.28,
    noiseMix: 0,
    cutoff: 460,
    resonance: 11,
    filterType: "lowpass",
    filterEnv: 0.82,
    attack: 0.006,
    decay: 0.2,
    sustain: 0.12,
    release: 0.1,
  },
  {
    name: "Bell",
    description: "Inharmonic sine with a long, ringing tail.",
    waveform: "sine",
    detune: 10,
    osc2Mix: 0.4,
    subMix: 0,
    noiseMix: 0.02,
    cutoff: 7200,
    resonance: 1.1,
    filterType: "lowpass",
    filterEnv: 0.18,
    attack: 0.003,
    decay: 0.85,
    sustain: 0.14,
    release: 2.4,
  },
  {
    name: "Sub Bass",
    description: "Round low end. Stay on the bottom octave.",
    waveform: "sawtooth",
    detune: 3,
    osc2Mix: 0.15,
    subMix: 0.72,
    noiseMix: 0,
    cutoff: 340,
    resonance: 2.4,
    filterType: "lowpass",
    filterEnv: 0.28,
    attack: 0.012,
    decay: 0.22,
    sustain: 0.86,
    release: 0.22,
  },
  {
    name: "Organ",
    description: "Fast square drawbar. Hold keys, no bloom.",
    waveform: "square",
    detune: 5,
    osc2Mix: 0.32,
    subMix: 0.22,
    noiseMix: 0,
    cutoff: 5200,
    resonance: 0.5,
    filterType: "lowpass",
    filterEnv: 0,
    attack: 0.005,
    decay: 0.06,
    sustain: 0.92,
    release: 0.07,
  },
  {
    name: "Air Keys",
    description: "Soft sine electric piano with a little dust.",
    waveform: "sine",
    detune: 6,
    osc2Mix: 0.28,
    subMix: 0.08,
    noiseMix: 0.06,
    cutoff: 3200,
    resonance: 0.8,
    filterType: "lowpass",
    filterEnv: 0.32,
    attack: 0.012,
    decay: 0.55,
    sustain: 0.45,
    release: 0.7,
  },
];

export const DEFAULT_PATCH: Patch = {
  name: "Bright Lead",
  description: "Immediate saw lead with a little width and bite.",
  waveform: "sawtooth",
  detune: 8,
  osc2Mix: 0.42,
  subMix: 0.12,
  noiseMix: 0,
  cutoff: 2800,
  resonance: 1.6,
  filterType: "lowpass",
  filterEnv: 0.38,
  attack: 0.01,
  decay: 0.18,
  sustain: 0.58,
  release: 0.28,
};
